package org.usfirst.frc.team2168.robot;
import java.awt.Font;
import java.text.*;
import java.util.*;

import javax.swing.*;
import javax.swing.event.ChangeEvent;
import javax.swing.event.ChangeListener;

public class SliderFrame extends javax.swing.JFrame {
    
    /**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Double var;

	/** Creates new form SliderFrame */
    public SliderFrame(Double var) {
    	this.var = var;
        initComponents();
        
        //prepare labels, the only hand edited piece
        Format f = new DecimalFormat("0.0");
        Hashtable<Integer, JComponent> labels = new Hashtable<Integer, JComponent>();
        for(int i=0;i<=100;i+=10){
            JLabel label = new JLabel(f.format(i*0.01));
            label.setFont(label.getFont().deriveFont(Font.PLAIN));
            labels.put(i,label);
        }
        slider.setLabelTable(labels);
        //end of my own code, the rest is done by NetBeans
        

        setVisible(true);  
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        slider = new javax.swing.JSlider();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        slider.setMajorTickSpacing(10);
        slider.setMaximum(100);
        slider.setPaintLabels(true);
        slider.setPaintTicks(true);
        slider.setValue(50);
        slider.addChangeListener(new MyChangeAction());
        slider.setPreferredSize(new java.awt.Dimension(500, 46));
        getContentPane().add(slider, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

    }
    
    // Variables declaration - do not modify
    protected javax.swing.JSlider slider;
    // End of variables declaration
 
    public class MyChangeAction implements ChangeListener{

    	//complete code here

    	public void stateChanged(ChangeEvent ce) 
    	{ 
    	double value = slider.getValue(); 
    	var = value/100;
    	System.out.println(var);
    	repaint();


    	}
    
}
}
